### ISSUE TITLE
Issue in getting relationship type from the raw CSV file into the mapped JSON file.

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/mapper-ijic#12]
Hello Team,

We are working on the ICIJ data to generate a graph to show the nodes and its links.

We need to bind the link label for each of the links shown in the graph. Refer the image attached.

![linklabel](https://user-images.githubusercontent.com/48215082/76426126-a1601f00-63d0-11ea-8143-7ff2f3f5bcc5.png)

From those file we can see a column "link" which has the data we need to display in the graph.
offshore_leaks.edges.csv from csv_offshore_leaks.2018-02-14
panama_papers.edges.csv from csv_panama_papers.2018-02-14
paradise_papers.edges.csv from csv_paradise_papers.2018-02-14

But we don't have such value in the mapped json file which is mapped followed by the instructions here https://github.com/Senzing/mapper-ijic.

We suspect that there is an issue mapping the file.

Can you figure this out and assist us how to get the link type from CSV file into the JSON file?

Thanks.

**Comment by jbutcher21** [comment]
What you need is the match_key.   I did a getEntityByEntityID on Kam Fung ...

![image](https://user-images.githubusercontent.com/22121925/76444891-dc873180-6381-11ea-9583-00bf1288f8e5.png)

Two things:  We only stored the high level link, not the sub-role because it was not often present.   Secondly, "The Bearer" as a name was filtered out as a generic value.    When you see an ENTITY_NAME of blank... you should display "Unknown" or "The Bearer" on IJIC data if you prefer. 

![image](https://user-images.githubusercontent.com/22121925/76445425-9ed6d880-6382-11ea-916b-be4bc0b0db1e.png)

Let me know if you have any further questions.

**Comment by jbutcher21** [comment]
Latest update gets the role as the relationship type.
